on: push

name: Create Release

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.1"
      - name: Install dependencies
        run:  make install_dependencies
      - name: Build
        run:  make build_cli
      - name: Test
        run: make run_tests
