on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.1"
      - name: Install dependencies
        run:  make install_dependencies 
      - name: Build
        run: make build_cli
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ""
          draft: false
          prerelease: false
      - name: Attach asset
        uses: AButler/upload-release-assets@v2.0
        with:
          files: './bin/swarm'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
